dataset:
  name: "msmarco-passage/dev"
  index_path: "indexes/msmarco_passage"
  max_dev_queries: 500

retrieval:
  bm25_num_results: 100

evaluation:
  metrics:
    - "recip_rank"
    - "ndcg_cut_10"
    - "recall_100"
    
query_expansion:
  method: "RM3"
  fb_docs: 10
  fb_terms: 10
  original_query_weight: 0.6